# Generated by Django 4.2.6 on 2024-01-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Userprofiledetail',
        ),
    ]
